#pragma once
/*
   This file has been generated by IDA.
   It contains local type definitions from
   the type library 'sonicbackup'
*/

#define __int8 char
#define __int16 short
#define __int32 int
#define __int64 long long

/* 135 */
enum ChaoType : __int8
{
	ChaoType_Empty = 0x0,
	ChaoType_Egg = 0x1,
	ChaoType_Child = 0x2,
	ChaoType_Good = 0x3,
	ChaoType_Bad = 0x4,
	ChaoType_Neutral_Normal = 0x5,
	ChaoType_Hero_Normal = 0x6,
	ChaoType_Dark_Normal = 0x7,
	ChaoType_Neutral_Swim = 0x8,
	ChaoType_Hero_Swim = 0x9,
	ChaoType_Dark_Swim = 0xA,
	ChaoType_Neutral_Fly = 0xB,
	ChaoType_Hero_Fly = 0xC,
	ChaoType_Dark_Fly = 0xD,
	ChaoType_Neutral_Run = 0xE,
	ChaoType_Hero_Run = 0xF,
	ChaoType_Dark_Run = 0x10,
	ChaoType_Neutral_Power = 0x11,
	ChaoType_Hero_Power = 0x12,
	ChaoType_Dark_Power = 0x13,
	ChaoType_Neutral_Chaos = 0x14,
	ChaoType_Hero_Chaos = 0x15,
	ChaoType_Dark_Chaos = 0x16,
	ChaoType_Tails = 0x17,
	ChaoType_Knuckles = 0x18,
	ChaoType_Amy = 0x19,
};

/* 137 */
enum SADXBodyType : __int8
{
	SADXBodyType_Normal = 0x0,
	SADXBodyType_EggChao = 0x1,
	SADXBodyType_Omochao = 0x2,
	SADXBodyType_None = 0x3,
};

/* 561 */
enum SA2BAnimal : __int8
{
	SA2BAnimal_None = 0xFF,
	SA2BAnimal_Penguin = 0x0,
	SA2BAnimal_Seal = 0x1,
	SA2BAnimal_Otter = 0x2,
	SA2BAnimal_Rabbit = 0x3,
	SA2BAnimal_Cheetah = 0x4,
	SA2BAnimal_Warthog = 0x5,
	SA2BAnimal_Bear = 0x6,
	SA2BAnimal_Tiger = 0x7,
	SA2BAnimal_Gorilla = 0x8,
	SA2BAnimal_Peacock = 0x9,
	SA2BAnimal_Parrot = 0xA,
	SA2BAnimal_Condor = 0xB,
	SA2BAnimal_Skunk = 0xC,
	SA2BAnimal_Sheep = 0xD,
	SA2BAnimal_Raccoon = 0xE,
	SA2BAnimal_HalfFish = 0xF,
	SA2BAnimal_SkeletonDog = 0x10,
	SA2BAnimal_Bat = 0x11,
	SA2BAnimal_Dragon = 0x12,
	SA2BAnimal_Unicorn = 0x13,
	SA2BAnimal_Phoenix = 0x14,
	SA2BAnimal_YellowChaosDrive = 0x15,
	SA2BAnimal_GreenChaosDrive = 0x16,
	SA2BAnimal_RedChaosDrive = 0x17,
	SA2BAnimal_PurpleChaosDrive = 0x18,
};

/* 1087 */

struct  ChaoEmotions
{
	__int16 field_124;
	__int16 Category1Timer;
	__int16 SicknessTimer;
	__int16 Category2Timer;
	char Joy;
	char Anger;
	char UrgeToCry;
	char Fear;
	char Surprise;
	char Dizziness;
	char Relax;
	char Total;
	__int16 Sleepiness;
	__int16 Tiredness;
	__int16 Hunger;
	__int16 MateDesire;
	__int16 Boredom;
	__int16 Lonely;
	__int16 Tire;
	__int16 Stress;
	__int16 Nourish;
	__int16 Conditn;
	__int16 Energy;
	char Normal_Curiosity;
	char Kindness;
	char CryBaby_Energetic;
	char Naive_Normal;
	char Solitude;
	char Vitality;
	char Glutton;
	char Regain;
	char Skillful;
	char Charm;
	char Chatty;
	char Normal_Carefree;
	char Fickle;
	char FavoriteFruit;
	char field_158[2];
	char CoughLevel;
	char ColdLevel;
	char RashLevel;
	char RunnyNoseLevel;
	char HiccupsLevel;
	char StomachAcheLevel;
};

struct ChaoCharacterBond
{
	char a;
	char b;
	__int16 field_2;
	__int16 field_4;
};


/* 478 */
typedef unsigned __int8 Uint8;

/* 630 */
struct ChaoDNAGrade
{
	Uint8 gradeA;
	Uint8 gradeB;
};

/* 567 */

struct ChaoDNA
{
	char ResetTrigger;
	char field_1[91];
	ChaoDNAGrade StatGrades[9];
	char field_6E;
	char field_6F;
	char field_70;
	char field_71;
	char field_72;
	char field_73;
	char field_74;
	int field_75;
	char field_79;
	char field_7A;
	char field_7B;
	int field_7C;
	int field_80;
	int field_84;
	int field_88;
	__int16 field_8C;
	char FavoriteFruit1;
	char FavoriteFruit2;
	char field_4C8[4];
	char Color1;
	char Color2;
	char MonotoneFlag1;
	char MonotoneFlag2;
	char Texture1;
	char Texture2;
	char ShinyFlag1;
	char ShinyFlag2;
	char EggColor1;
	char EggColor2;
	char gap_4D6[6];
};


/* 138 */
enum SADXAnimal : __int8
{
	SADXAnimal_None = 0xFF,
	SADXAnimal_Seal = 0x0,
	SADXAnimal_Penguin = 0x1,
	SADXAnimal_Otter = 0x2,
	SADXAnimal_Peacock = 0x3,
	SADXAnimal_Swallow = 0x4,
	SADXAnimal_Parrot = 0x5,
	SADXAnimal_Deer = 0x6,
	SADXAnimal_Rabbit = 0x7,
	SADXAnimal_Kangaroo = 0x8,
	SADXAnimal_Gorilla = 0x9,
	SADXAnimal_Lion = 0xA,
	SADXAnimal_Elephant = 0xB,
	SADXAnimal_Mole = 0xC,
	SADXAnimal_Koala = 0xD,
	SADXAnimal_Skunk = 0xE,
};

/* 1049 */
struct  ChaoDataBase {
	char gap_0[18];
	char Name[7];
	char gap_19[7];
	char SwimFraction;
	char FlyFraction;
	char RunFraction;
	char PowerFraction;
	char StaminaFraction;
	char LuckyFraction;
	char IntelligenceFraction;
	char UnknownFraction;
	char StatGrades[8];
	char StatLevels[8];
	__int16 StatPoints[8];
	char field_48[56];
	ChaoType Type;
	char Garden;
	__int16 Happiness;
	__int16 InKindergarten;
	__int16 ClockRollovers;
	__int16 field_88;
	__int16 Lifespan;
	__int16 Lifespan2;
	__int16 Reincarnations;
	char field_90[24];
	float PowerRun;
	float FlySwim;
	float Alignment;
	char gap_B4[12];
	float EvolutionProgress;
	char gap_C4[13];
	char EyeType;
	char MouthType;
	char BallType;
	char gap_D4;
	char Headgear;
	char HideFeet;
	char Medal;
	char Color;
	char MonotoneHighlights;
	char Texture;
	char Shiny;
	char EggColor;
	SADXBodyType BodyType;
	char BodyTypeAnimal;
	char field_E1[39];
	__int16 DoctorMedal;
	char field_10A[14];
	int SA2AnimalBehavior;
	SA2BAnimal SA2BArmType;
	SA2BAnimal SA2BEarType;
	SA2BAnimal SA2BForeheadType;
	SA2BAnimal SA2BHornType;
	SA2BAnimal SA2BLegType;
	SA2BAnimal SA2BTailType;
	SA2BAnimal SA2BWingType;
	SA2BAnimal SA2BFaceType;
	ChaoEmotions Emotion;
	char ClassRoomFlags[4];
	__int16 SA2BToys;
	__int16 field_166;
	__int16 field_168;
	__int16 field_16A;
	ChaoCharacterBond SA2BCharacterBonds[6];
	char field_190[680];
	ChaoDNA DNA;
	int field_4DC;
	int SADXAnimalBehaviors;
	SADXAnimal ArmType;
	SADXAnimal EarType;
	SADXAnimal EyebrowType;
	SADXAnimal ForeheadType;
	SADXAnimal LegType;
	SADXAnimal TailType;
	SADXAnimal WingType;
	SADXAnimal UnknownType;
	char field_4EC[12];
	ChaoCharacterBond SADXCharacterBonds[6];
};

struct ChaoData
{
	ChaoDataBase data;
	char field_520[736];
};
